/**
 * [BETA] Qovery API
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is in Beta and still in progress. Some endpoints are not available yet. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support+api+documentation@qovery.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ApplicationGitRepositoryRequest } from './ApplicationGitRepositoryRequest';
import { ApplicationPortResponse } from './ApplicationPortResponse';
import { ApplicationPortResponsePorts } from './ApplicationPortResponsePorts';
import { ApplicationStorageResponse } from './ApplicationStorageResponse';
import { ApplicationStorageResponseStorage } from './ApplicationStorageResponseStorage';
import { Healthcheck } from './Healthcheck';
import { HttpFile } from '../http/http';

export class ApplicationEditRequest {
    /**
    * name is case insensitive
    */
    'name'?: string;
    /**
    * give a description to this application
    */
    'description'?: string;
    'gitRepository'?: ApplicationGitRepositoryRequest;
    /**
    * `DOCKER` requires `dockerfile_path` `BUILDPACKS` does not require any `dockerfile_path` 
    */
    'buildMode'?: ApplicationEditRequestBuildModeEnum;
    /**
    * The path of the associated Dockerfile
    */
    'dockerfilePath'?: string;
    /**
    * Development language of the application
    */
    'buildpackLanguage'?: ApplicationEditRequestBuildpackLanguageEnum;
    /**
    * unit is millicores (m). 1000m = 1 cpu
    */
    'cpu'?: number;
    /**
    * unit is MB. 1024 MB = 1GB
    */
    'memory'?: number;
    /**
    * Minimum number of instances running. This resource auto-scale based on the CPU and Memory consumption. Note: 0 means that there is no application running. 
    */
    'minRunningInstances'?: number;
    /**
    * Maximum number of instances running. This resource auto-scale based on the CPU and Memory consumption. Note: -1 means that there is no limit. 
    */
    'maxRunningInstances'?: number;
    'healthcheck'?: Healthcheck;
    /**
    * Specify if the environment preview option is activated or not for this application. If activated, a preview environment will be automatically cloned at each pull request. 
    */
    'autoPreview'?: boolean;
    /**
    * Specify if the sticky session option (also called persistant session) is activated or not for this application. If activated, user will be redirected by the load balancer to the same instance each time he access to the application. 
    */
    'stickySession'?: boolean;
    'storage'?: Array<ApplicationStorageResponseStorage>;
    'ports'?: Array<ApplicationPortResponsePorts>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "gitRepository",
            "baseName": "git_repository",
            "type": "ApplicationGitRepositoryRequest",
            "format": ""
        },
        {
            "name": "buildMode",
            "baseName": "build_mode",
            "type": "ApplicationEditRequestBuildModeEnum",
            "format": ""
        },
        {
            "name": "dockerfilePath",
            "baseName": "dockerfile_path",
            "type": "string",
            "format": ""
        },
        {
            "name": "buildpackLanguage",
            "baseName": "buildpack_language",
            "type": "ApplicationEditRequestBuildpackLanguageEnum",
            "format": ""
        },
        {
            "name": "cpu",
            "baseName": "cpu",
            "type": "number",
            "format": ""
        },
        {
            "name": "memory",
            "baseName": "memory",
            "type": "number",
            "format": ""
        },
        {
            "name": "minRunningInstances",
            "baseName": "min_running_instances",
            "type": "number",
            "format": ""
        },
        {
            "name": "maxRunningInstances",
            "baseName": "max_running_instances",
            "type": "number",
            "format": ""
        },
        {
            "name": "healthcheck",
            "baseName": "healthcheck",
            "type": "Healthcheck",
            "format": ""
        },
        {
            "name": "autoPreview",
            "baseName": "auto_preview",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "stickySession",
            "baseName": "sticky_session",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "storage",
            "baseName": "storage",
            "type": "Array<ApplicationStorageResponseStorage>",
            "format": ""
        },
        {
            "name": "ports",
            "baseName": "ports",
            "type": "Array<ApplicationPortResponsePorts>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ApplicationEditRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

