/**
 * [BETA] Qovery API
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is in Beta and still in progress. Some endpoints are not available yet. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support+api+documentation@qovery.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class MetricCPUDatapointResponse {
    'createdAt': Date;
    'requestedInNumber'?: number;
    'consumedInNumber': number;
    'consumedInPercent': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "requestedInNumber",
            "baseName": "requested_in_number",
            "type": "number",
            "format": ""
        },
        {
            "name": "consumedInNumber",
            "baseName": "consumed_in_number",
            "type": "number",
            "format": ""
        },
        {
            "name": "consumedInPercent",
            "baseName": "consumed_in_percent",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MetricCPUDatapointResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

