/**
 * [BETA] Qovery API
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is in Beta and still in progress. Some endpoints are not available yet. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support+api+documentation@qovery.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CommunityUsage } from './CommunityUsage';
import { CommunityUsageResponse } from './CommunityUsageResponse';
import { Cost } from './Cost';
import { CurrentCost } from './CurrentCost';
import { PaidUsage } from './PaidUsage';
import { PaidUsageResponse } from './PaidUsageResponse';
import { RemainingCredits } from './RemainingCredits';
import { HttpFile } from '../http/http';

export class OrganizationCurrentCostResponse {
    'plan'?: OrganizationCurrentCostResponsePlanEnum;
    /**
    * number of days remaining before the end of the trial period
    */
    'remainingTrialDay'?: number;
    'remainingCredits'?: RemainingCredits;
    'cost'?: Cost;
    'paidUsage'?: PaidUsageResponse;
    'communityUsage'?: CommunityUsageResponse;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "plan",
            "baseName": "plan",
            "type": "OrganizationCurrentCostResponsePlanEnum",
            "format": ""
        },
        {
            "name": "remainingTrialDay",
            "baseName": "remaining_trial_day",
            "type": "number",
            "format": ""
        },
        {
            "name": "remainingCredits",
            "baseName": "remaining_credits",
            "type": "RemainingCredits",
            "format": ""
        },
        {
            "name": "cost",
            "baseName": "cost",
            "type": "Cost",
            "format": ""
        },
        {
            "name": "paidUsage",
            "baseName": "paid_usage",
            "type": "PaidUsageResponse",
            "format": ""
        },
        {
            "name": "communityUsage",
            "baseName": "community_usage",
            "type": "CommunityUsageResponse",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return OrganizationCurrentCostResponse.attributeTypeMap;
    }

    public constructor() {
    }
}


export type OrganizationCurrentCostResponsePlanEnum = "COMMUNITY" | "FREE" | "PROFESSIONAL" | "BUSINESS" ;

