/**
 * [BETA] Qovery API
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is in Beta and still in progress. Some endpoints are not available yet. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support+api+documentation@qovery.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class PaidUsageResponse {
    'maxDeploymentsPerMonth'?: number;
    'consumedDeployments'?: number;
    'monthlyPlanCost'?: number;
    'monthlyPlanCostInCents'?: number;
    'remainingDeployments'?: number;
    'deploymentsExceeded'?: boolean;
    'renewalAt'?: Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "maxDeploymentsPerMonth",
            "baseName": "max_deployments_per_month",
            "type": "number",
            "format": ""
        },
        {
            "name": "consumedDeployments",
            "baseName": "consumed_deployments",
            "type": "number",
            "format": ""
        },
        {
            "name": "monthlyPlanCost",
            "baseName": "monthly_plan_cost",
            "type": "number",
            "format": ""
        },
        {
            "name": "monthlyPlanCostInCents",
            "baseName": "monthly_plan_cost_in_cents",
            "type": "number",
            "format": ""
        },
        {
            "name": "remainingDeployments",
            "baseName": "remaining_deployments",
            "type": "number",
            "format": ""
        },
        {
            "name": "deploymentsExceeded",
            "baseName": "deployments_exceeded",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "renewalAt",
            "baseName": "renewal_at",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return PaidUsageResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

