/**
 * Qovery API
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development. 
 *
 * OpenAPI spec version: 1.0.3
 * Contact: support+api+documentation@qovery.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ApplicationDeploymentRestriction {
    /**
    * Match mode will rebuild app only if specified items are updated. Exclude mode will not rebuild app if specified items are updated.
    */
    'mode': ApplicationDeploymentRestrictionModeEnum;
    'type': ApplicationDeploymentRestrictionTypeEnum;
    'value': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "mode",
            "baseName": "mode",
            "type": "ApplicationDeploymentRestrictionModeEnum",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "ApplicationDeploymentRestrictionTypeEnum",
            "format": ""
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ApplicationDeploymentRestriction.attributeTypeMap;
    }

    public constructor() {
    }
}


export type ApplicationDeploymentRestrictionModeEnum = "MATCH" | "EXCLUDE" ;
export type ApplicationDeploymentRestrictionTypeEnum = "FILE" | "PATH" ;

