/**
 * Qovery API
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development. 
 *
 * OpenAPI spec version: 1.0.2
 * Contact: support+api+documentation@qovery.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BillingEnd } from './BillingEnd';
import { BillingStart } from './BillingStart';
import { HttpFile } from '../http/http';

export class BillingPeriod {
    'billingStartedOn'?: Date;
    'billingEndedOn'?: Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "billingStartedOn",
            "baseName": "billing_started_on",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "billingEndedOn",
            "baseName": "billing_ended_on",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return BillingPeriod.attributeTypeMap;
    }

    public constructor() {
    }
}

