/**
 * Qovery API
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support+api+documentation@qovery.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ClusterStatusResponse {
    'clusterId'?: string;
    'status'?: ClusterStatusResponseStatusEnum;
    'isDeployed'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "clusterId",
            "baseName": "cluster_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "ClusterStatusResponseStatusEnum",
            "format": ""
        },
        {
            "name": "isDeployed",
            "baseName": "is_deployed",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ClusterStatusResponse.attributeTypeMap;
    }

    public constructor() {
    }
}


export type ClusterStatusResponseStatusEnum = "READY" | "DEPLOYMENT_QUEUED" | "DEPLOYING" | "DEPLOYMENT_ERROR" | "DEPLOYED" | "STOP_QUEUED" | "STOPPING" | "STOP_ERROR" | "STOPPED" | "DELETE_QUEUED" | "DELETING" | "DELETE_ERROR" | "DELETED" | "RUNNING" | "RUNNING_ERROR" ;

