/**
 * Qovery API
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support+api+documentation@qovery.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CostRangeResponse {
    'minCostInCents'?: number;
    'minCost'?: number;
    'maxCostInCents'?: number;
    'maxCost'?: number;
    'currencyCode': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "minCostInCents",
            "baseName": "min_cost_in_cents",
            "type": "number",
            "format": ""
        },
        {
            "name": "minCost",
            "baseName": "min_cost",
            "type": "number",
            "format": ""
        },
        {
            "name": "maxCostInCents",
            "baseName": "max_cost_in_cents",
            "type": "number",
            "format": ""
        },
        {
            "name": "maxCost",
            "baseName": "max_cost",
            "type": "number",
            "format": ""
        },
        {
            "name": "currencyCode",
            "baseName": "currency_code",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CostRangeResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

