/**
 * Qovery API
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development. 
 *
 * OpenAPI spec version: 1.0.3
 * Contact: support+api+documentation@qovery.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CreditCardResponse {
    'id': string;
    'createdAt': Date;
    'expiryMonth': number;
    'expiryYear': number;
    'lastDigit': string;
    'isExpired': boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "expiryMonth",
            "baseName": "expiry_month",
            "type": "number",
            "format": ""
        },
        {
            "name": "expiryYear",
            "baseName": "expiry_year",
            "type": "number",
            "format": ""
        },
        {
            "name": "lastDigit",
            "baseName": "last_digit",
            "type": "string",
            "format": ""
        },
        {
            "name": "isExpired",
            "baseName": "is_expired",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreditCardResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

