/**
 * Qovery API
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support+api+documentation@qovery.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Cost } from './Cost';
import { RemainingCredits } from './RemainingCredits';
import { HttpFile } from '../http/http';

export class CurrentCost {
    'plan'?: CurrentCostPlanEnum;
    /**
    * number of days remaining before the end of the trial period
    */
    'remainingTrialDay'?: number;
    'remainingCredits'?: RemainingCredits;
    'cost'?: Cost;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "plan",
            "baseName": "plan",
            "type": "CurrentCostPlanEnum",
            "format": ""
        },
        {
            "name": "remainingTrialDay",
            "baseName": "remaining_trial_day",
            "type": "number",
            "format": ""
        },
        {
            "name": "remainingCredits",
            "baseName": "remaining_credits",
            "type": "RemainingCredits",
            "format": ""
        },
        {
            "name": "cost",
            "baseName": "cost",
            "type": "Cost",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CurrentCost.attributeTypeMap;
    }

    public constructor() {
    }
}


export type CurrentCostPlanEnum = "COMMUNITY" | "FREE" | "PROFESSIONAL" | "BUSINESS" ;

