/**
 * [BETA] Qovery API
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is in Beta and still in progress. Some endpoints are not available yet. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support+api+documentation@qovery.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DatabaseVersionMode } from './DatabaseVersionMode';
import { HttpFile } from '../http/http';

export class DatabaseConfigurationResponse {
    'databaseType'?: DatabaseConfigurationResponseDatabaseTypeEnum;
    'version'?: Array<DatabaseVersionMode>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "databaseType",
            "baseName": "database_type",
            "type": "DatabaseConfigurationResponseDatabaseTypeEnum",
            "format": ""
        },
        {
            "name": "version",
            "baseName": "version",
            "type": "Array<DatabaseVersionMode>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DatabaseConfigurationResponse.attributeTypeMap;
    }

    public constructor() {
    }
}


export type DatabaseConfigurationResponseDatabaseTypeEnum = "POSTGRESQL" | "MYSQL" | "MONGODB" | "REDIS" ;

