/**
 * Qovery API
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development. 
 *
 * OpenAPI spec version: 1.0.2
 * Contact: support+api+documentation@qovery.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BaseResponse } from './BaseResponse';
import { DeploymentHistoryApplicationResponse } from './DeploymentHistoryApplicationResponse';
import { DeploymentHistoryDatabaseResponse } from './DeploymentHistoryDatabaseResponse';
import { HttpFile } from '../http/http';

export class DeploymentHistoryEnvironmentResponse {
    'status'?: DeploymentHistoryEnvironmentResponseStatusEnum;
    'applications'?: Array<DeploymentHistoryApplicationResponse>;
    'databases'?: Array<DeploymentHistoryDatabaseResponse>;
    'id': string;
    'createdAt': Date;
    'updatedAt'?: Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "status",
            "baseName": "status",
            "type": "DeploymentHistoryEnvironmentResponseStatusEnum",
            "format": ""
        },
        {
            "name": "applications",
            "baseName": "applications",
            "type": "Array<DeploymentHistoryApplicationResponse>",
            "format": ""
        },
        {
            "name": "databases",
            "baseName": "databases",
            "type": "Array<DeploymentHistoryDatabaseResponse>",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return DeploymentHistoryEnvironmentResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

