/**
 * Qovery API
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development. 
 *
 * OpenAPI spec version: 1.0.2
 * Contact: support+api+documentation@qovery.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EnvironmentLogResponseScope } from './EnvironmentLogResponseScope';
import { HttpFile } from '../http/http';

export class EnvironmentLogResponse {
    'id': string;
    'createdAt': Date;
    'scope'?: EnvironmentLogResponseScope;
    /**
    * Status is a state machine. It starts with `BUILDING` or `DEPLOYING` state (or `INITIALIZED`if auto-deploy is deactivated). Then finish with `*_ERROR` or any termination state. 
    */
    'state'?: EnvironmentLogResponseStateEnum;
    /**
    * Log message
    */
    'message': string;
    /**
    * Only for errors. Helps Qovery team to investigate.
    */
    'executionId'?: string;
    'hint'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "scope",
            "baseName": "scope",
            "type": "EnvironmentLogResponseScope",
            "format": ""
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "EnvironmentLogResponseStateEnum",
            "format": ""
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string",
            "format": ""
        },
        {
            "name": "executionId",
            "baseName": "execution_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "hint",
            "baseName": "hint",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return EnvironmentLogResponse.attributeTypeMap;
    }

    public constructor() {
    }
}


export type EnvironmentLogResponseStateEnum = "BUILD_ERROR" | "BUILDING" | "BUILT" | "DELETE_ERROR" | "DELETED" | "DELETING" | "DEPLOYED" | "DEPLOYING" | "DEPLOYMENT_ERROR" | "INITIALIZED" | "QUEUED" | "RUNNING" | "RUNNING_ERROR" | "STOP_ERROR" | "STOPPED" | "STOPPING" ;

