/**
 * Qovery API
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development. 
 *
 * OpenAPI spec version: 1.0.2
 * Contact: support+api+documentation@qovery.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { StorageDiskResponse } from './StorageDiskResponse';
import { HttpFile } from '../http/http';

export class EnvironmentApplicationsStorageResponse {
    'application': string;
    'disks'?: Array<StorageDiskResponse>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "application",
            "baseName": "application",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "disks",
            "baseName": "disks",
            "type": "Array<StorageDiskResponse>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return EnvironmentApplicationsStorageResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

