/**
 * Qovery API
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support+api+documentation@qovery.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BaseResponse } from './BaseResponse';
import { ReferenceObject } from './ReferenceObject';
import { HttpFile } from '../http/http';

export class EnvironmentResponse {
    /**
    * name is case insensitive
    */
    'name': string;
    'project'?: ReferenceObject;
    /**
    * uuid of the user that made the last update
    */
    'lastUpdatedBy'?: string;
    'cloudProvider': any;
    'mode': EnvironmentResponseModeEnum;
    'clusterId': string;
    'id': string;
    'createdAt': Date;
    'updatedAt'?: Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "project",
            "baseName": "project",
            "type": "ReferenceObject",
            "format": ""
        },
        {
            "name": "lastUpdatedBy",
            "baseName": "last_updated_by",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "cloudProvider",
            "baseName": "cloud_provider",
            "type": "any",
            "format": ""
        },
        {
            "name": "mode",
            "baseName": "mode",
            "type": "EnvironmentResponseModeEnum",
            "format": ""
        },
        {
            "name": "clusterId",
            "baseName": "cluster_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return EnvironmentResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

