/**
 * Qovery API
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support+api+documentation@qovery.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EnvironmentDatabasesCurrentMetricResponseCpu } from './EnvironmentDatabasesCurrentMetricResponseCpu';
import { EnvironmentDatabasesCurrentMetricResponseMemory } from './EnvironmentDatabasesCurrentMetricResponseMemory';
import { HttpFile } from '../http/http';

export class InstanceResponse {
    'createdAt'?: Date;
    'name'?: string;
    'cpu'?: EnvironmentDatabasesCurrentMetricResponseCpu;
    'memory'?: EnvironmentDatabasesCurrentMetricResponseMemory;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "cpu",
            "baseName": "cpu",
            "type": "EnvironmentDatabasesCurrentMetricResponseCpu",
            "format": ""
        },
        {
            "name": "memory",
            "baseName": "memory",
            "type": "EnvironmentDatabasesCurrentMetricResponseMemory",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return InstanceResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

