/**
 * [BETA] Qovery API
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is in Beta and still in progress. Some endpoints are not available yet. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support+api+documentation@qovery.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BaseResponse } from './BaseResponse';
import { URI } from './URI';
import { HttpFile } from '../http/http';

export class MemberResponse {
    'name'?: string;
    'nickname'?: string;
    'email': string;
    'profilePictureUrl'?: URI;
    /**
    * last time the user was connected
    */
    'lastActivityAt'?: Date;
    'role'?: MemberResponseRoleEnum;
    'id': string;
    'createdAt': Date;
    'updatedAt'?: Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "nickname",
            "baseName": "nickname",
            "type": "string",
            "format": ""
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": "email"
        },
        {
            "name": "profilePictureUrl",
            "baseName": "profile_picture_url",
            "type": "URI",
            "format": "uri"
        },
        {
            "name": "lastActivityAt",
            "baseName": "last_activity_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "role",
            "baseName": "role",
            "type": "MemberResponseRoleEnum",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return MemberResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

