/**
 * Qovery API
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development. 
 *
 * OpenAPI spec version: 1.0.2
 * Contact: support+api+documentation@qovery.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class MetricMemoryDatapointResponse {
    'createdAt': Date;
    'requestedInMb': number;
    'consumedInMb': number;
    'consumedInPercent': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "requestedInMb",
            "baseName": "requested_in_mb",
            "type": "number",
            "format": ""
        },
        {
            "name": "consumedInMb",
            "baseName": "consumed_in_mb",
            "type": "number",
            "format": ""
        },
        {
            "name": "consumedInPercent",
            "baseName": "consumed_in_percent",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MetricMemoryDatapointResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

