/**
 * Qovery API
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development. 
 *
 * OpenAPI spec version: 1.0.2
 * Contact: support+api+documentation@qovery.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BaseResponse } from './BaseResponse';
import { OrganizationRequest } from './OrganizationRequest';
import { HttpFile } from '../http/http';

export class OrganizationResponse {
    /**
    * uuid of the user owning the organization
    */
    'owner'?: string;
    'id': string;
    'createdAt': Date;
    'updatedAt'?: Date;
    /**
    * name is case insensitive
    */
    'name': string;
    'description'?: string;
    'plan': OrganizationResponsePlanEnum;
    'websiteUrl'?: string;
    'repository'?: string;
    'logoUrl'?: string;
    'iconUrl'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "owner",
            "baseName": "owner",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "plan",
            "baseName": "plan",
            "type": "OrganizationResponsePlanEnum",
            "format": ""
        },
        {
            "name": "websiteUrl",
            "baseName": "website_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "repository",
            "baseName": "repository",
            "type": "string",
            "format": ""
        },
        {
            "name": "logoUrl",
            "baseName": "logo_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "iconUrl",
            "baseName": "icon_url",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return OrganizationResponse.attributeTypeMap;
    }

    public constructor() {
    }
}


export type OrganizationResponsePlanEnum = "COMMUNITY" | "FREE" | "PROFESSIONAL" | "BUSINESS" ;

