/**
 * Qovery API
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development. 
 *
 * OpenAPI spec version: 1.0.3
 * Contact: support+api+documentation@qovery.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ScalewayCredentialsRequest {
    'name': string;
    'scalewayAccessKey'?: string;
    'scalewaySecretKey'?: string;
    'scalewayProjectId'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "scalewayAccessKey",
            "baseName": "scaleway_access_key",
            "type": "string",
            "format": ""
        },
        {
            "name": "scalewaySecretKey",
            "baseName": "scaleway_secret_key",
            "type": "string",
            "format": ""
        },
        {
            "name": "scalewayProjectId",
            "baseName": "scaleway_project_id",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ScalewayCredentialsRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

