/**
 * Qovery API
 * - Qovery is the fastest way to deploy your full-stack apps on any Cloud provider. - ℹ️ The API is stable and still in development. 
 *
 * OpenAPI spec version: 1.0.2
 * Contact: support+api+documentation@qovery.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VariableImportRequestVars } from './VariableImportRequestVars';
import { HttpFile } from '../http/http';

export class VariableImportRequest {
    'overwrite': boolean;
    'vars': Array<VariableImportRequestVars>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "overwrite",
            "baseName": "overwrite",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "vars",
            "baseName": "vars",
            "type": "Array<VariableImportRequestVars>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return VariableImportRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

